[package]
name = "simpleterm"
version = "0.1.0"
authors = ["Trevan Haskell <dev@trevanhaskell.com>"]
edition = "2018"

[dependencies]
ggez = "0.5.1"
rand = "0.7"
cgmath = { version = "0.17", features = ["mint"]}
