[package]
name = "simpleterm"
version = "0.1.0"
authors = ["Trevan Haskell <dev@trevanhaskell.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "0.109.0"
